###
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email":"ivan@email.ru",
  "password":"12345678"
}

> {% client.global.set("auth_token", response.body.token);%}
###
GET http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/groups
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name":"class"
}

###
PUT http://localhost:8080/groups/642d3da8f172c8790a4a6416
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name":"club"
}
### Delete group
DELETE http://localhost:8080/groups/642be4fc2c3af6341b43ea43
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Delete members from group
DELETE http://localhost:8080/groups/642d3da8f172c8790a4a6416/deleteMembers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

["642bed748fc793357ab7a9d9"]

### Add members
POST http://localhost:8080/groups/642d3da8f172c8790a4a6416/addMembers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

["642bed748fc793357ab7a9d9","642bfe28552bfd2d434a8896"]

