### Authorization by token
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email": "kk@email.ru",
  "password": "123"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("auth_token", response.body.token);
%}

###
GET http://localhost:8080/tasks
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "date": "2023-05-11T14:00:00Z",
  "title": "shopping"
}
###
PUT http://localhost:8080/tasks/642a91666dd75105070ced36
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
"date": "2023-05-01T14:00:00Z",
"title": "running"
}

###
DELETE http://localhost:8080/tasks/642a91666dd75105070ced36
Authorization: Bearer {{auth_token}}

