### Authorization by token
POST http://localhost:8080/auth/authenticate
Content-Type: application/json

{
  "email":"ivan@email.ru",
  "password":"12345678"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("auth_token", response.body.token);
%}

### Get all tasks
GET http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "sortingMethod": "defaultDesc",
  "dateStart": "2023-01-01T09:00:00Z",
  "dateFinish": "2023-07-01T16:00:00Z"
}

### Get tasks from group
GET http://localhost:8080/tasks/642d3da8f172c8790a4a6416
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{

  "dateStart": "2023-01-01T09:00:00Z",
  "dateFinish": "2023-06-01T16:00:00Z"
}

### Add new task
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "dateStart": "2023-04-11T23:31:00Z",
  "dateFinish": "2023-04-11T23:59:00Z",
  "title": "workout"
}
###
POST http://localhost:8080/tasks/642d3da8f172c8790a4a6416
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "date": "2023-01-11T13:00:00Z",
  "title": "do project"
}
### Edit task
PUT http://localhost:8080/tasks/64314624667c5b379168283d
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
"dateStart": "2023-01-08T14:00:00Z",
  "dateFinish": "2023-01-08T15:00:00Z",
"title": "class"
}

### FINISH TASK
PUT http://localhost:8080/tasks/finish/6435105fd585040eb76b7c68
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Set notification
PUT http://localhost:8080/tasks/6435108ad585040eb76b7c69/setNotification
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
 "alarmBefore": "3",
  "unitsType": "hours"
}

###
DELETE http://localhost:8080/tasks/64311aa4592b162873254229
Authorization: Bearer {{auth_token}}

